### PR TITLE
[refactor] - fixed Dockerfile linter issues

### PR DESCRIPTION
**Pull request by mur-me**
## Description

main fix DL3025 - use arguments JSON notation for CMD and ENTRYPOINT arguments, start to use ENTRYPOINT in JSON notation with CMD - it allows users to overwrite default stable CMD arguments minor stuff:

    DL3027-Do not use apt as it is meant to be an end-user tool, use apt-get or apt-cache instead
    DL3042 - Avoid cache directory with pip install --no-cache-dir

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Something else (simple changes that are not related to existing functionality or others)

## Tested on my 1.0.7 setup

### CODE REVIEW

**Comment by seonggwonyoon** [comment]
This dockerfile does not work.
Check this error please.

```
Run command

docker build -t bifrost-relayer . --no-cache
docker run -d --mount type=bind,source="$(pwd)"/configs,target=/app/configs  --name relayer --network host -e PRIVATE_KEY=0x1231231231231231231231231231231231231231231231231231231231231231 bifrost-relayer
```

```
Error Message

docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "python relayer-launcher.py": executable file not found in $PATH: unknown.
```

**Comment by mur-me** [comment]
Hi @seonggwonyoon,
I don't know my state when I've tested it, but you are right, it wasn't working, sorry and thanks for testing it.

I've fixed with adding `"/bin/bash","-c"` into ENTRYPOINT instruction.

How it looks like now:
```
docker top relayer
a28e407f20ba06e7e52a0e49bc8434c9da33352fe1d8f2ece4b2d68fd6703b3f
UID                 PID                 PPID                C                   STIME               TTY                 TIME                CMD
root                99761               99742               0                   10:57               ?                   00:00:00            python relayer-launcher.py
```
Previously:
```
docker top ubuntu_relayer_1 
UID                 PID                 PPID                C                   STIME               TTY                 TIME                CMD
root                803177              803158              0                   07:46               ?                   00:00:00            /bin/sh -c python relayer-launcher.py launch -k $PRIVATE_KEY
root                803226              803177              0                   07:46               ?                   00:00:06            python relayer-launcher.py launch -k 0x0000000000000000000000000
``` 


Why do you need this:
The shell form prevents any CMD or run command line arguments from being used, but has the disadvantage that your ENTRYPOINT will be started as a subcommand of /bin/sh -c, which does not pass signals. This means that the executable will not be the container’s PID 1 - and will not receive Unix signals - so your executable will not receive a SIGTERM from docker stop

More info:
https://github.com/hadolint/hadolint/wiki/DL3025

**Comment by mur-me** [comment]
And my 0x4CAd798bdeAabD117687E28C4b868769C81ecA62 validator is still active and healthy with this new approach

**Comment by seonggwonyoon** [comment]
> Hi @seonggwonyoon, I don't know my state when I've tested it, but you are right, it wasn't working, sorry and thanks for testing it.
> 
> I've fixed with adding `"/bin/bash","-c"` into ENTRYPOINT instruction.
> 
> How it looks like now:
> 
> ```
> docker top relayer
> a28e407f20ba06e7e52a0e49bc8434c9da33352fe1d8f2ece4b2d68fd6703b3f
> UID                 PID                 PPID                C                   STIME               TTY                 TIME                CMD
> root                99761               99742               0                   10:57               ?                   00:00:00            python relayer-launcher.py
> ```
> 
> Previously:
> 
> ```
> docker top ubuntu_relayer_1 
> UID                 PID                 PPID                C                   STIME               TTY                 TIME                CMD
> root                803177              803158              0                   07:46               ?                   00:00:00            /bin/sh -c python relayer-launcher.py launch -k $PRIVATE_KEY
> root                803226              803177              0                   07:46               ?                   00:00:06            python relayer-launcher.py launch -k 0x0000000000000000000000000
> ```
> 
> Why do you need this: The shell form prevents any CMD or run command line arguments from being used, but has the disadvantage that your ENTRYPOINT will be started as a subcommand of /bin/sh -c, which does not pass signals. This means that the executable will not be the container’s PID 1 - and will not receive Unix signals - so your executable will not receive a SIGTERM from docker stop
> 
> More info: https://github.com/hadolint/hadolint/wiki/DL3025

Perfect!

**Review by seonggwonyoon — APPROVED** [review]

**Pull request merged**
